baseurl = "/"
title = "openEuler"
theme = "project"
themesDir = "./themes"

disablePathToLower = true
pluralizelisttitles = false

# Site language. Available translations in the theme's `/i18n` directory.
languageCode = "en-us"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

uglyURLs = true
buildFuture = true

# Define the number of posts per page
paginate = 10

[taxonomies]
    tag = "tags"
    archive = "archives"

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/en"
    weight = 1

[[menu.main]]
    identifier = "community"
    name = "Community"
    weight = 3
    hasChilren = true

[[menu.main]]
    identifier = "developer"
    name = "Developer"
    url = "/en/developer.html"
    weight = 1
    parent = "community"

[[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/en/events.html"
    parent = "community"
    weight = 2

[[menu.main]]
    identifier = "sig"
    name = "SIG (Special Interest Group)"
    url = "/en/sig.html"
    weight = 3
    parent = "community"

[[menu.main]]
    identifier = "members"
    name = "Members"
    url = "/en/building/members.html"
    weight = 4
    parent = "community"

[[menu.main]]
    identifier = "integrationCertification"
    name = "Integration & Certification"
    url = "/en/community/integrationandcertification.html"
    weight = 5
    parent = "community"

[[menu.main]]
    identifier = "mails"
    name = "Mail Lists"
    url = "/en/community/mails.html"
    parent = "community"
    weight = 11

[[menu.main]]
    identifier = "irc"
    name = "IRC"
    url = "/en/community/irc.html"
    parent = "community"
    weight = 9

[[menu.main]]
    identifier = "meetings"
    name = "Meetings"
    url = "/en/meetings.html"
    parent = "community"
    weight = 11


[[menu.main]]
    identifier = "summit"
    name = "Virtual Summit"
    url = "/en/summit/2020-virtual-summit.html"
    parent = "community"
    weight = 10


[[menu.main]]
    identifier="blog"
    name = "Blog"
    url  = "/en/blog.html"
    weight = 2

[[menu.main]]
    identifier = "docs"
    name = "Docs"
    url  = "/en/docs.html"
    weight = 5
    hasChildren = true

[[menu.main]]
    identifier = "1.0_BASE"
    name = "1.0 BASE"
    parent = "docs"
    url = "/en/docs/1.0_Base/docs/Installation/Installation.html"
    weight = 2


[[menu.main]]
    identifier = "20.03_LTS"
    name = "20.03 LTS"
    parent = "docs"
    url = "/en/docs/20.03_LTS/docs/Releasenotes/release_notes.html"
    weight = 2

# [[menu.main]]
#    identifier = "releases"
#    name = "Releases"
#    url  = "/en/releases.html"
#    weight = 6

[[menu.main]]
    identifier = "download"
    name = "Download"
    url  = "/en/download.html"
    weight = 7

[[menu.main]]
    identifier = "security"
    name = "Security"
    weight = 8
    hasChidren = true

[[menu.main]]
    identifier = "subMitIssue"
    name = "Submit a cve issue"
    url  = "/en/security.html"
    weight = 1
    parent = "security"

[[menu.main]]
    identifier = "Advisories"
    name = "Security Advisories"
    url  = "https://cve.openeuler.org/#/home?lang=en"
    weight = 2
    parent = "security"

[[menu.main]]
    identifier = "CVE"
    name = "CVE"
    url  = "https://cve.openeuler.org/#/CVE?lang=en"
    weight = 3
    parent = "security"

[[menu.main]]
    identifier = "lang"
    name = "中文"
    url = "/zh"
    weight = 9

# Menu chinese
[[languages.zh.menu.main]]
    dentifier="home"
    name = "首页"
    url  = "/zh"
    weight = 1

[[languages.zh.menu.main]]
    identifier = "community"
    name = "社区"
    weight = 3
    hasChilren = true

[[languages.zh.menu.main]]
    identifier = "developer"
    name = "开发者"
    url = "/zh/developer.html"
    weight = 1
    parent = "community"

[[languages.zh.menu.main]]
    identifier = "events"
    name = "活动"
    url = "/zh/events.html"
    parent = "community"
    weight = 2

[[languages.zh.menu.main]]
    identifier = "sig"
    name = "SIG（项目组）"
    url = "/zh/sig.html"
    weight = 3
    parent = "community"

[[languages.zh.menu.main]]
    identifier = "members"
    name = "会员"
    url = "/zh/building/members.html"
    weight = 4
    parent = "community"

[[languages.zh.menu.main]]
    identifier = "integrationCertification"
    name = "集成&认证"
    url = "/zh/community/integrationandcertification.html"
    weight = 5
    parent = "community"

[[languages.zh.menu.main]]
    identifier = "mails"
    name = "邮件列表"
    url = "/zh/community/mails.html"
    parent = "community"
    weight = 11

[[languages.zh.menu.main]]
    identifier = "irc"
    name = "IRC"
    url = "/zh/community/irc.html"
    parent = "community"
    weight = 9

[[languages.zh.menu.main]]    
    identifier = "meetings"
    name = "会议"
    url = "/zh/meetings.html"
    parent = "community"
    weight = 11


[[languages.zh.menu.main]]    
    identifier = "summit"
    name = "社区峰会"
    url = "/zh/summit/2020-virtual-summit.html"
    parent = "community"
    weight = 10


[[languages.zh.menu.main]]
    identifier="blog"
    name = "博客"
    url  = "/zh/blog.html"
    weight = 2

[[languages.zh.menu.main]]
    identifier = "docs"
    name = "文档"
    url  = "/zh/docs/home.html"
    weight = 5
    hasChidren = true

[[languages.zh.menu.main]]
    identifier = "1.0_BASE"
    name = "1.0 BASE"
    parent = "docs"
    url = "/zh/docs/1.0_Base/docs/Releasenotes/release_notes.html"
    weight = 2

[[languages.zh.menu.main]]
    identifier = "20.03_LTS"
    name = "20.03 LTS"
    parent = "docs"
    url = "/zh/docs/20.03_LTS/docs/Releasenotes/release_notes.html"
    weight = 2
#[[languages.zh.menu.main]]
#    identifier = "release"
#    name = "发行说明"
#    parent = "docs"
#    url = "/zh/docs/Releasenotes/release_notes.html"
#    weight = 2

#[[languages.zh.menu.main]]
#    identifier = "install"
#    name = "安装指南"
#   parent = "docs"
#    url = "/zh/docs/Installation/installation.html"
#    weight=3

#[[languages.zh.menu.main]]
#    identifier = "management"
#    name = "管理员指南"
#    parent = "docs"
#    url = "/zh/docs/Administration/administration.html"
#    weight = 4

#[[languages.zh.menu.main]]
#    identifier = "secHarden"
#    name = "安全加固指南"
#    parent = "docs"
#   url = "/zh/docs/SecHarden/secHarden.html"
#    weight = 5

#[[languages.zh.menu.main]]
#    identifier = "vitrual"
#    name = "虚拟化用户指南"
#    parent = "docs"
#    url = "/zh/docs/Virtualization/virtualization.html"
#    weight = 6

#[[languages.zh.menu.main]]
#    identifier = "container"
#    name = "容器用户指南"
#    parent = "docs"
#    url = "/zh/docs/Container/container.html"
#    weight = 7

#[[languages.zh.menu.main]]
#    identifier = "releases"
#    name = "版本"
#    url  = "/zh/releases.html"
#    weight = 7

[[languages.zh.menu.main]]
    identifier = "download"
    name = "下载"
    url  = "/zh/download.html"
    weight = 8

[[languages.zh.menu.main]]
    identifier = "security"
    name = "安全"
    
    weight = 9
    hasChidren = true

[[languages.zh.menu.main]]
    identifier = "subMitIssue"
    name = "漏洞上报"
    url  = "/zh/security.html"
    weight = 1
    parent = "security"

[[languages.zh.menu.main]]
    identifier = "Advisories"
    name = "安全公告"
    url  = "https://cve.openeuler.org/#/home?lang=zh"
    weight = 2
    parent = "security"

[[languages.zh.menu.main]]
    identifier = "CVE"
    name = "CVE"
    url  = "https://cve.openeuler.org/#/CVE?lang=zh"
    weight = 3
    parent = "security"

[[languages.zh.menu.main]]
    identifier = "lang"
    name = "EN"
    url = "/en"
    weight = 10

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://gitee.com/openeuler"
    pre = "<i class='fa fa-2x fa-github'></i>"


[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:freesky.edward@gmail.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/news/"
    author = "openEuler"
    defaultKeywords = ["devows", "hugo", "go", "openEuler"]
    defaultDescription = "Site template made by devcows Modified by openEuler team"

    # Twitter
    # twitter = "GoHugoIO"
    # twitterImage = "img/twitter-default.png"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Enable the contact form by entering your Formspree.io email
    email = "contact@openeuler.org"
    contact_form_ajax = false

    about_us = "<p>We are an open source orgnization provides open source software.</p>"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    logo = "img/openeuler.png"
    logo_small = "img/openeuler.png"
    address = """<p><strong>openEuler, io.</strong>
        <br>
        <br>Newtown upon River
        <br>Beijing
        <br>
        <strong>China</strong>
      </p>
      """
    #latitude = "-12.043333"
    #longitude = "-77.028333"
    
    ### DOC Configurations
    BookRepo = 'https://gitee.com/openeuler/docs/blob'
    BookEditPath= 'blob/master/content'
    BookDateFormat = 'Jan 2, 2019'
    enableGitInfo = true
    BookMenuBundle = '/menu'
    bookHidden = true
    bookFlatSection = true

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us by freesky.edward@gmail.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = false
    archives = true

[params.cards]
    enable = true


# cards 
[[params.card]]
    image = "/img/1.svg"
    title = "Contributions"
    url = "/en/developer.html"
    description = "We appreciate your ideas and contributions"
    weight = 1

[[params.card]]
    image = "/img/2.svg"
    title = "Quick Start"
    url = "/en/docs/20.03_LTS/docs/Quickstart/quick-start.html"
    description = "Tutorial guide for you a quick start"
    weight = 2

[[params.card]]
    image = "/img/3.svg"
    title = "Members"
    url = "/en/building/members.html"
    description = "Trustworthy memberships in this community"
    weight = 3

[[params.card]]
    image = "/img/4.svg"
    title = "Integration & Certification"
    url = "/en/community/integrationandcertification.html"
    description = "Integrate your drivers, middlewares and apps with openEuler and get certified."
    weight = 4

#  chinese cards
[[languages.zh.params.card]]
    image = "/img/1.svg"
    title = "社区贡献"
    url = "/zh/developer.html"
    description = "不管您是初学者还是有经验的开发者，这里将帮助您快速参与贡献。"
    weight = 1

[[languages.zh.params.card]]
    image = "/img/2.svg"
    title = "快速入门"
    url = "/zh/docs/20.03_LTS/docs/Quickstart/quick-start.html"
    description = "如果您想要尝试使用openEuler，这里提供教程助您快速入门。"
    weight = 2

[[languages.zh.params.card]]
    image = "/img/3.svg"
    title = "社区会员"
    url = "/zh/building/members.html"
    description = "了解社区会员，欢迎贵公司或者组织加入我们成为社区一员。"
    weight = 3

[[languages.zh.params.card]]
    image = "/img/4.svg"
    title = "集成&认证"
    url = "/zh/community/integrationandcertification.html"
    description = "将您的驱动、中间件和应用与openEuler进行集成及认证。"
    weight = 4

# why party configuration
[params.why]
    enable = true

[params.emails]
    enable = true

[params.news]
    enable = true

[params.blog]
    enable = true

[params.events]
    enable = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Do you want to contribute?"
    subtitle = "We apprecite your contribution, whill all related projects are open source."
    link_url = "https://gitee.com/openeuler/"
    link_text = "Go To Source"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Partners"
    subtitle = ""


[params.recent_posts]
    enable = true
    title = "From our news"
    subtitle = "There are many events ocur since we announce open source, Please keep an your eye on us."

[params.copyright]
    enable = true
    text = "<span><a href=\"/en/brand.html\">Brand</a><a href=\"/en/legal.html\">Private Policy</a><a href=\"/en/legal.html\">Legal Notice</a></span><p>Copyright © openEuler 2020. All rights reserved.</p>"

[languages.zh.params.copyright]
    enable = true
    text = "<span><a href=\"/zh/brand.html\">品牌</a><a href=\"/zh/legal.html\">法律声明</a><a href=\"/zh/privacyPolicy.html\">隐私政策</a></span><p>版权所有 © openEuler 2020 保留一切权利</p>"

[languages]

[languages.en]
    languageCode = "en-us"
    contentDir = "content/en"

[languages.zh]
    languageCode = "zh-cn"
    contentDir = "content/zh"

# Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://valine.js.org
  [params.valine]
    enable = true
    appId = 'KcTcd38EvA1I33vSIV6qWNea-gzGzoHsz'
    appKey = 'oJBVUOcItn0essSFvY6tS77O'
    notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
    verify = false # Verification code
    avatar = 'mm'
    placeholder = 'Please leave a message...'
    visitor = true


